const projectData = [
  {
    id : 0,
    title : 'PokemonDex',
    overview : 'React, pokeAPI, Axios를 사용하여 다양한 포켓몬의 데이터를 검색하고, 선택한 포켓몬의 정보를 제공하는 웹 애플리케이션입니다.',
    img : `${process.env.PUBLIC_URL}/img/pokemondex.png`,
    useSkill : ['REACT', 'AXIOS', 'pokeAPI'],
    url : 'https://ztarc12.github.io/pokemondex',
    github: 'https://github.com/ztarc12/pokemondex',
  },
  {
    id : 1,
    title : 'Hoflix',
    overview : 'React Hook, TMDB API, Axios를 사용하여 다양한 장르의 영화를 검색하고, 선택한 영화의 상세 정보와 유사한 영화를 추천하는 기능을 제공하는 웹 애플리케이션입니다.',
    img : `${process.env.PUBLIC_URL}/img/hoflix.png`,
    useSkill : ['REACT HOOK', 'AXIOS', 'TMDB'],
    url : 'https://ztarc12.github.io/movieapp_hoflix',
    github: 'https://github.com/ztarc12/movieapp_hoflix/tree/main',
  },
  {
    id : 2,
    title : 'CardGame',
    overview : 'React와 상태 관리(state)를 사용하여 카드 짝 맞추기 게임을 구현한 웹 애플리케이션입니다.',
    img : `${process.env.PUBLIC_URL}/img/cardgame.png`,
    useSkill : ['REACT', 'STATE'],
    url : 'https://ztarc12.github.io/cardGame',
    github: 'https://github.com/ztarc12/cardGame',
  },
  {
    id : 3,
    title : 'ColorPalette',
    overview : 'React, 상태 관리(state), Axios를 사용하여 다양한 색상 팔레트를 생성하고 색상 코드를 복사할 수 있는 웹 애플리케이션입니다.',
    img : `${process.env.PUBLIC_URL}/img/colorspalette.png`,
    useSkill : ['REACT', 'STATE', 'AXIOS'],
    url : 'https://ztarc12.github.io/colorsPalette/',
    github: 'https://github.com/ztarc12/colorsPalette',
  },
  {
    id : 4,
    title : 'DutchPay',
    overview : 'HTML5, CSS3, JavaScript, 및 LocalStorage를 사용하여 더치페이를 계산하고 관리하는 웹 애플리케이션입니다.',
    img : `${process.env.PUBLIC_URL}/img/dutchPay.png`,
    useSkill : ['HTML5', 'CSS3', 'JAVASCRIPT', 'LOCALSTORAGE'],
    url : 'https://ztarc12.github.io/dutchPay/',
    github: 'https://github.com/ztarc12/dutchPay',
  },
  {
    id : 5,
    title : 'TodoList',
    overview : 'HTML, CSS, JavaScript, LocalStorage, 및 OpenWeatherMap API를 사용하여 할 일 목록을 관리하고 현재 날씨 정보를 제공하는 웹 애플리케이션입니다.',
    img : `${process.env.PUBLIC_URL}/img/todoList.png`,
    useSkill : ['HTML5','CSS3','JAVASCRIPT', 'LOCALSTORAGE', 'WEATHER API'],
    url : 'https://ztarc12.github.io/todoList/',
    github: 'https://github.com/ztarc12/todoList',
  },
  {
    id : 6,
    title : '포트폴리오 페이지',
    overview : 'React로 제작한 포트폴리오 이며, 현재 보고 계신 웹 페이지 입니다.',
    img : `${process.env.PUBLIC_URL}/img/portfolio.png`,
    useSkill : ['HTML5','CSS3','REACT'],
    url : 'https://ztarc12.github.io/portfolio/',
    github: 'https://github.com/ztarc12/portfolio/tree/master',
  },
  {
    id : 7,
    title : '삼성물산 리뉴얼 랜딩페이지(2021)',
    overview : 'React로 제작한 포트폴리오 이며, 현재 보고 계신 웹 페이지 입니다.',
    img : `${process.env.PUBLIC_URL}/img/samsung_project.png`,
    useSkill : ['HTML5','CSS3','JAVASCRIPT','jQuery'],
    url : 'https://ztarc12.github.io/samsung_project/',
    github: 'https://github.com/ztarc12/samsung_project',
  },
  {
    id : 8,
    title : '이월드 리뉴얼 랜딩페이지(2021)',
    overview : 'React로 제작한 포트폴리오 이며, 현재 보고 계신 웹 페이지 입니다.',
    img : `${process.env.PUBLIC_URL}/img/eworld_project.png`,
    useSkill : ['HTML5','CSS3','JAVASCRIPT','jQuery'],
    url : 'https://ztarc12.github.io/eworld_project/',
    github: 'https://github.com/ztarc12/eworld_project',
  },
]

export default projectData